parameters:
    seo:
        title: "HNK Framework"

services:
    hnk_framework.seo_manager:
        class: Hnk\HnkFrameworkBundle\Seo\SeoManager
        arguments: ["%seo.title%"]

    hnk_framework.twig.seo_extension:
        class: Hnk\HnkFrameworkBundle\Twig\SeoExtension
        arguments: ["@hnk_framework.seo_manager"]
        tags:
            - { name: twig.extension }
